### PR TITLE
CLI: Throw error if `--requireReference` and `--unsafeSkipStorageCheck` are both enabled

### PR DESCRIPTION
**Pull request by ericglau**
The `requireReference` option is used for requiring a reference contract for storage compatibility checks, which contradicts with `unsafeSkipStorageCheck`.  Throw an error if both are enabled.

### CODE REVIEW

**Comment by Amxx** [comment]
What is the argument for ignoring (silently) vs throwing an "incompatible options" error ?

**Comment by ernestognw** [comment]
Same concern as @Amxx, the CLI arguments are contradictory and it's not obvious what the behavior would be.

**Comment by ericglau** [comment]
Thanks, I agree with the comments.  Changed it to throw an error if both are enabled.

**Review by ernestognw — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
