### PR TITLE
added brownie documentation

### PR DESCRIPTION
**Pull request by PatrickAlphaC**

### CODE REVIEW

**Comment by thegismar** [comment]
Very nice.

**Comment by PatrickAlphaC** [comment]
Let me know if/what I can do to help here! I wasn’t exactly sure how to run this locally… readme didn’t mention contributing

**Comment by frangio** [comment]
Thank you for this contribution @PatrickAlphaC.

Unfortunately we won't merge it because as the content you wrote states, the Upgrades Plugins do not support Brownie. As you show it's perfectly possible to use the proxy contracts by themselves with Brownie but the value added by these plugins is: 1) 
orchestration of the different contracts that have to be deployed, and 2) important security checks.

I invite you to share this guide with our community over at https://forum.openzeppelin.com.

**Comment by PatrickAlphaC** [comment]
@frangio ah too bad. Well thank you for the thought out comment here! I'll have to share the package with the community then.

Thanks for all the work you've been putting into these contracts though!

**Comment by jjhesk** [comment]
@frangio I am interested to develop the py version for the upgrading module. Can you tell me the brief operation procedure for the upgrading process in flow chart?

**Comment by PatrickAlphaC** [comment]
@jjhesk check this for examples: https://github.com/brownie-mix/upgrades-mix

**Pull request closed without merging**
