### PR TITLE
include openethereum dev chain in recognised dev chains

### PR DESCRIPTION
**Pull request by jamie-arpeggi**

### CODE REVIEW

**Comment by Amxx** [comment]
Note: it looks like there is some network using that chain id
https://chainlist.org/chain/17

**Comment by ericglau** [comment]
> Note: it looks like there is some network using that chain id https://chainlist.org/chain/17

I don't see any [blocks on that chain](https://exp.thaifi.com/blocks) in the past 6 months so I think this is fine.

**Review by ericglau — APPROVED** [review]
Thanks for the PR

**Comment by ericglau** [comment]
@jamie-arpeggi OpenEthereum is now deprecated (references: [1](https://github.com/openethereum/openethereum), [2](https://twitter.com/OpenEthereumOrg/status/1529147048758595585)) so we've reverted this change.  Thanks for your understanding.

**Pull request merged**
