### PR TITLE
Add admin.getInstance

### PR DESCRIPTION
**Pull request by pinglamb**
This PR is for kicking off #173.

An `deployedProxyAdmin` method is added to `admin` module to get `ProxyAdmin` instance (feel free to suggest names). My use case is simply to get the address programmatically without `fs.readFileSync` the manifest.

### CODE REVIEW

**Comment by pinglamb** [comment]
@frangio Please feel free to suggest the proper naming and code structure. Thanks!

**Comment by frangio** [comment]
Thanks @pinglamb! What is the reason for exposing it as a function (i.e. `upgrades.admin.deployedProxyAdmin()`) rather than just a getter (`upgrades.admin.instance`)?

**Comment by pinglamb** [comment]
It seems that if it is an instance, once `hre.upgrades` is called it will try to load the `ProxyAdmin` object. For example, if you are using it for the first time, it will throw the `No ProxyAdmin ...` error. Also I am not sure if there will be other issues if we are caching the contract object with `hre.upgrades`. I guess the safest is loading it on demand? What do you think?

**Comment by frangio** [comment]
Yes that makes sense. I think the function name `getInstance` sounds better to me. It's used as `upgrades.admin.getInstance()`.

We have to add the same function in the Truffle plugin. The code is very similar. Can you do these changes?

**Review by frangio — APPROVED** [review]
Thank you @pinglamb! I've changed the tests a little to give us more confidence that the return value is correct.

**Pull request merged**
