### PR TITLE
Add support for user defined value types

### LINKED ISSUE #477: Support user defined value types.
When using user defined value types (available since 0.8.8) the ast-dereferencer fails.

```
Compiling 111 files with 0.8.10
An unexpected error occurred:

Error: No node with id 25034 of type StructDefinition,EnumDefinition
    at deref (projectRoot/node_modules/@openzeppelin/upgrades-core/src/ast-dereferencer.ts:38:11)
    at projectRoot/node_modules/@openzeppelin/upgrades-core/src/utils/curry.ts:11:19
    at extractStorageLayout (projectRoot/node_modules/@openzeppelin/upgrades-core/src/storage/extract.ts:59:29)
    at validate (projectRoot/node_modules/@openzeppelin/upgrades-core/src/validate/run.ts:165:67)
    at OverriddenTaskDefinition._action (projectRoot/node_modules/@openzeppelin/hardhat-upgrades/src/index.ts:62:25)
    at Environment._runTaskDefinition (projectRoot/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at Environment.run (projectRoot/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)
    at SimpleTaskDefinition.action (projectRoot/node_modules/hardhat/src/builtin-tasks/compile.ts:975:37)
    at Environment._runTaskDefinition (projectRoot/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at Environment.run (projectRoot/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)
error Command failed with exit code 1.
```

Apparently, using [this contract](https://github.com/Amxx/openzeppelin-contracts/blob/breaking/Timers/udvt/contracts/utils/Timers.sol) replicated the issue.

Simple contract to reproduce the current error and test support:

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.9;

contract UserDefinedValueType {
    type Timestamp is uint64;
}
```

Note: As mentioned in https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/438 we need to be careful with Solidity 0.8.8 because it has buggy storage layout rules, they were fixed in 0.8.9. We should probably reject 0.8.8.

### PR DESCRIPTION
**Pull request by frangio**
Fixes https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/438
Fixes #477 

User defined value types are not supported without storage layout info, this is fine because they only exist in >=0.8.8, and I think we always have storage layout info for those versions. Unsure about Truffle to be honest, do we have storage layout in Truffle?

### CODE REVIEW

**Comment by frangio** [comment]
I added tests for when we don't have detailed layout info (specifically `numberOfBytes`). I don't think we can currently support that on Truffle, any upgrade involving UDVTs will result in an error. The way that I would like us to support that is to check that original and upgraded contracts were compiled with >= 0.8.9, but we don't currently have the version information along with the layout.

**Comment by KholdStare** [comment]
Hi @frangio. I just tested out this particular commit on my local codebase, and now I am getting a different error further along, still to do with User Defined Value Types. 

```
Error: No node with id 10052 of type StructDefinition,EnumDefinition,ContractDefinition
    at deref (/home/kholdstare/workspace/code/crypto/evm/node_modules/@openzeppelin/upgrades-core/src/ast-dereferencer.ts:38:11)
    at curried (/home/kholdstare/workspace/code/crypto/evm/node_modules/@openzeppelin/upgrades-core/src/utils/curry.ts:13:14)
    at serializeTypeName (/home/kholdstare/workspace/code/crypto/evm/node_modules/@openzeppelin/upgrades-core/src/utils/function.ts:22:31)
    at /home/kholdstare/workspace/code/crypto/evm/node_modules/@openzeppelin/upgrades-core/src/utils/function.ts:52:72
    at Array.map (<anonymous>)
    at getFunctionSignature (/home/kholdstare/workspace/code/crypto/evm/node_modules/@openzeppelin/upgrades-core/src/utils/function.ts:52:55)
    at /home/kholdstare/workspace/code/crypto/evm/node_modules/@openzeppelin/upgrades-core/src/validate/run.ts:173:45
    at Array.map (<anonymous>)
    at validate (/home/kholdstare/workspace/code/crypto/evm/node_modules/@openzeppelin/upgrades-core/src/validate/run.ts:173:12)
    at OverriddenTaskDefinition._action (/home/kholdstare/workspace/code/crypto/evm/node_modules/@openzeppelin/hardhat-upgrades/src/index.ts:81:25)
```

I can help out to narrow down a minimal example contract, but I don't know how to find out what node `10052` is referencing in the ast. Are there any artifacts I can look at or generate that will tell me what node `10052` is, and what contract it's in?

**Comment by frangio** [comment]
Thanks for testing. The ids are present in the AST in `artifacts/build-info` files. I was able to reproduce the issue though.

**Comment by KholdStare** [comment]
@frangio I tested on the commit in this PR (e75232f), and it no longer crashes! 🎉

**Review by ericglau — APPROVED** [review]
LGTM!

**Comment by ericglau** [comment]
Can you also add a changelog entry?

**Comment by frangio** [comment]
Done!

**Pull request merged**
