### PR TITLE
feature: Add deployer options as an argument

### PR DESCRIPTION
**Pull request by pedrobranco**
Draft PR for an initial proposal for fixing #85. 

I've only implemented `from` argument since other options doesn't seem so relevant as a custom deploy address.

### CODE REVIEW

**Comment by frangio** [comment]
Thanks for giving this a shot @pedrobranco!

Let's see, there's several transactions for each `deployProxy` or `upgradeProxy` function call:

1. Implementation contract deployment
2. Admin contract deployment
3. Proxy contract deployment
4. Upgrade function call

In your PR you seem to only have used the `from` parameter for the first two. Why not also for the proxy?

For the function call it doesn't make as much sense because we should infer the sender from the admin contract (though we don't do this yet).

**Comment by pedrobranco** [comment]
> In your PR you seem to only have used the from parameter for the first two. Why not also for the proxy?

True, didn't noticed it. The main goal here is to replace the default account when deploying, so for all of those transactions still seems fine.

> For the function call it doesn't make as much sense because we should infer the sender from the admin contract (though we don't do this yet).

Should we do it in this PR?

**Comment by pedrobranco** [comment]
BTW, tests are failing with:
```
Error: while migrating AdminUpgradeabilityProxy: Invalid number of parameters for "undefined". Got 4 expected 3!
```
And by reverting the corresponding [this change](https://github.com/OpenZeppelin/openzeppelin-upgrades/pull/213/files#diff-5b7495dacd28e6c5dadbc547df0dcfeb1de99e63039fed72f19ecd949b3eddd2R48) also fails in `upgradeProxy`:
```
Error: Invalid number of parameters for "upgrade". Got 3 expected 2!
    at upgradeProxy (<REDACTED>/openzeppelin-upgrades/packages/plugin-truffle/src/upgrade-proxy.ts:84:15)

```
Seems that isn't allowing to pass the Web3 options. Correct me if I'm wrong but it seems like an issue already reported here: https://github.com/trufflesuite/truffle/issues/3506

**Comment by pedrobranco** [comment]
@frangio can you help clarify these issues?

**Comment by frangio** [comment]
@pedrobranco Sorry about the delay!

There does seem to be an underlying issue with Truffle. It's closer to https://github.com/trufflesuite/truffle/issues/2843 than the one you shared. But our situation is also a little bit different, see my comment https://github.com/trufflesuite/truffle/issues/2843#issuecomment-739083982.

The issue is we are sending an empty object and Truffle doesn't recognize that it's meant to be a params object and so sends it as part of the constructor arguments.

We will have to avoid sending the params argument when we don't have any actual params to send.

**Comment by frangio** [comment]
I'm not sure when it will be released (later this week?) but Truffle has now fixed the problem you ran into in this PR.

https://github.com/trufflesuite/truffle/pull/3586

**Comment by frangio** [comment]
This branch is outdated now and would likely need to be rewritten.

This issue is being tracked in https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/85.

**Pull request closed without merging**
