### PR TITLE
Remove use of chalk.keyword

### PR DESCRIPTION
**Pull request by logvik**
Keyword has been removed. Need to use direct way.
https://github.com/chalk/chalk/issues/431

### CODE REVIEW

**Review by frangio — APPROVED** [review]
As far as I can tell it hasn't been removed yet, but I'm happy to make this change as soon as possible regardless.

Thank you!

**Review by frangio — CHANGES_REQUESTED** [review]
Actually, there's a few other instances of `chalk.keyword`. Can you update those as well?

**Comment by logvik** [comment]
Done. All "keywords" were removed.

**Review by frangio — APPROVED** [review]
Thank you!

**Pull request merged**
